# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registration_app', '0006_auto_20170817_1251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='review',
            name='stars',
            field=models.IntegerField(null=True),
        ),
    ]
